### ISSUE TITLE
Kloppen de emissie bestanden in calc wel?

### ISSUE THREAD

**Issue by Hilbrand** [stikstof/1.0#1]
In de calc mappen zie ik voor een aantal sectoren 1 emissiebestand met daarin zowel NOx als NH3 emissie en gezien de ctr bestanden lijkt het erop dat deze bestanden gebruikt zijn voor de berekeningen. Echter ops rekent 1 stof per run en alle emissiebronnen opgegeven in het emissiebestand worden ingelezen als de stof zoals opgegeven in het ctr bestand. Ik zou dus verwachten dat bij die sectoren met beide stoffen dat er 2 emissiebestanden aanwezig moeten zijn. Voor elke stof 1 apart bestand.

**Comment by stikstof** [comment]
goeie vraag!

Zo stond ik in de 1e run er ook in. Echter is in de 2e run vanuit 1 emissiebestand per stof (NOx / NH3) een doorrekening naar deposities uitgevoerd. 

In OPS is het dus vanuit 1 emissiebestand mogelijk om per stof (component) door te rekenen naar NH3 en NOx. 

NH3 en NOx zijn dus opgenomen in 1 emissiebestand.

**Comment by vriesdwj** [comment]
Het is een misverstand dat bronnen van verschillende stoffen met OPS-model in 1 keer doorgerekend zouden kunnen worden.
De stofspecifieke parameters (voor 1 stof) worden, zoals Hilbrand aangeeft, in het ctr bestand opgegeven. Alle bronnen die in het emissiebestand staan, dat in hetzelfde ctr bestand wordt aangegeven, worden dan doorgerekend met die stofspecifieke parameters. In het emissiebestand zelf zit dus geen informatie over de stof die het betreft.

Als de bronnen die zijn geleverd in de NH3 en NOx bestanden in 1 emissiebestand zijn opgenomen worden deze bij het doorrekenen, afhankelijk van de instellingen in het ctr bestand, als NH3 OF NOx beschouwd. De resultaten van zo'n run zijn dan niet bruikbaar.

Dus nogmaals, het is NIET mogelijk om vanuit 1 emissiebestand meerdere stoffen door te rekenen.

**Comment by stikstof** [comment]
@vriesdwj - juist! Daarom worden er ook 2 control files toegepast. 1 emissiebron-file wordt voor elke stof NH3 en NOx gebruikt. Dit is overeenkomstig met de wijze waarop met RIVM control files is gerekend.

**Comment by Hilbrand** [comment]
2 control files gebruiken is juist. Maar niet volledig. De control files bepalen welke emissie stof in het emissiebestand zitten. Dus als je zowel NOx als NH3 emissies in 1 bestand stopt worden die beide emissies met een NOx control file als NOx doorgerekend en met een NH3 control file als NH3 emissies. De stof genoemd aan het einde van elke regel in het emissiebestand geeft alleen aan om welke emissie het gaat, maar wordt **niet** als een soort 'filter' gebruikt door OPS om de specifieke emissie uit een bestand te halen.

In een aantal sectoren hier heb je de beide stoffen uit de 2 losse RIVM bestanden in 1 emissie.brn bestand gezet om zo tot emissies per sector te komen. Die emissie.brn bestanden zijn **niet** juist om gebruikt worden om een berekening te doen.

Tenzij je nog een script hebt dat voordat de emissie aan OPS wordt gegeven deze bestanden filtert. Dat kan natuurlijk. Dan zou er niets aan de hand zijn. Maar anders heb je onjuiste emissies gebruikt in de berekeningen voor die sectoren.

**Comment by Hilbrand** [comment]
Om de impact van het hier genoemde probleem te bepalen heb ik wat gedetaileerder gekeken. Met een eigen berekening van het emissiebestand van Afvalverwerking, zoals hier gepubliceerd, kom ik op dezelfde cijfers uit als in het hier gepubliceerde excel bestand. Daaruit kan ik concluderen dat er met verkeerde emissiecijfers gerekend is. Het emissiebestand bevat namelijk zowel NH3 als NOx emissies en er is dus geen andere 'filter' toegepast om de gegevens aan OPS mee te geven. Voor een juiste berekening had er een NH3 **_en_** een NOx bestand moeten zijn. Dit probleem is ook goed zichtbaar bij de depositie resultaten van de sector Bouw. In het emissiebestand van Bouw zitten **_geen_** emissies NH3, dus kan er ook **_geen_** depositie NH3 zijn. Echter er is hier wel een depositie resultatenbestand NH3 en in het excel bestand staat ook een cijfer bij NH3 depositie.

Het gevolg van deze fout is dat de cijfers voor alle sectoren, behalve buitenland, niet correct zijn. Buitenland bevat wel 2 emissiebestanden en lijkt daarmee wel juist te zijn doorgerekend. Intuïtief zou ik zeggen dat dit ook mogelijk de grote afwijking in cijfers zou kunnen verklaren. Maar dat kan uiteraard alleen worden vastgesteld door nieuwe berekeningen uit te voeren. Dus is het gevaarlijk om direct die conclusie te trekken. Mijn advies zou dan ook zijn om zo snel mogelijk een nieuwe berekening te doen met de juiste emissie cijfers.

Wat nog opviel is dat er een factor bij totale depositieberekening in de excel bestand is gebruikt waarbij NH3 met 0.82 en NOx met 0.3 wordt vermenigvuldigd om tot de totale depositie te komen. Ik kon geen verklaring voor die factoren vinden? Mogelijk klopt dat niet.

**Comment by vriesdwj** [comment]
@stikstof - Ben je het eens met de conclusie van Hilbrand: "Daaruit kan ik concluderen dat er met verkeerde emissiecijfers gerekend is." ?

**Comment by Geoneer** [comment]
Dank allemaal. We zijn met meerdere mensen de berekeningen opnieuw aan het uitvoeren. We werken onafhankelijk van elkaar. En jullie commentaar is uiteraard erg waardevol, zoals dat ook hoort te zijn in dit gehele proces.

**Comment by Nostragratus** [comment]
@Hilbrand 
1 kilo stikstofoxides = 0,3 kilo stikstof 
1 kilo ammoniak = 0,82 kilo stikstof 
Bron: https://www.wur.nl/upload_mm/e/c/d/2fce1598-fff7-4737-9319-8cbfa397664a_20191002%20factsheet%20Oenema.pdf
